databases:
    - id:  svcomp2012
      title:  SVCOMP 2012
      file: storage/svcomp2012.db
      default: false

    - id:   database_kernel2628
      title:  Linux Kernel 2.6.28
      file: storage/database.db
      default: true
